--BANCO DE DADOS PIZZARIA

-----------------------------------------------------------------------------------
-- Criando a tabela PEDIDO_VENDA
--------------------------------
CREATE TABLE [PEDIDO_VENDA]
(
    [COD_PEDIDO_VENDA] NVARCHAR(160)  NOT NULL,
    [COD_CLIENTE] NVARCHAR(160)  NOT NULL,
    [COD_VENDEDOR] NVARCHAR(160)  NOT NULL,
    [COD_SITUACAO_PEDIDO] NVARCHAR(160)  NOT NULL,
    [COD_FORMA_PAGAMENTO] NVARCHAR(160)  NOT NULL,
    [DATA_PEDIDO] DATETIME NOT NULL,
    [VLR_PEDIDO_VENDA] DOUBLE NOT NULL, 

    CONSTRAINT [PK_PEDIDO_VENDA] PRIMARY KEY ([COD_PEDIDO_VENDA]),
    CONSTRAINT [FK_COD_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES CLIENTE(COD_CLIENTE),
    CONSTRAINT [FK_COD_VENDEDOR] FOREIGN KEY ([COD_VENDEDOR]) REFERENCES VENDEDOR(COD_VENDEDOR),
    CONSTRAINT [FK_COD_SITUACAO_PEDIDO] FOREIGN KEY ([COD_SITUACAO_PEDIDO]) REFERENCES SITUACAO_PEDIDO(COD_SITUACAO_PEDIDO),
    CONSTRAINT [FK_COD_FORMA_PAGAMENTO] FOREIGN KEY ([COD_FORMA_PAGAMENTO]) REFERENCES FORMA_PAGAMENTO(COD_FORMA_PAGAMENTO)
);

CREATE UNIQUE INDEX [IPK_PEDIDO_VENDA] ON [PEDIDO_VENDA]([COD_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela VENDEDOR
---------------------------------
CREATE TABLE [VENDEDOR]
(
    [COD_VENDEDOR] NVARCHAR(160)  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    
    CONSTRAINT [PK_COD_VENDEDOR] PRIMARY KEY ([COD_VENDEDOR])
);

CREATE UNIQUE INDEX [IPK_COD_VENDEDOR] ON [VENDEDOR]([COD_VENDEDOR]);

-----------------------------------------------------------------------------------
-- Criando a tabela Produto
------------------------------------
CREATE TABLE [PRODUTO]
(
    [COD_PRODUTO] NVARCHAR(160) NOT NULL,
    [COD_TIPO_PRODUTO] NVARCHAR(160)  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [VLR_PRODUTO_COMPRA] DOUBLE NOT NULL,
    [VLR_PRODUTO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_PRODUTO] PRIMARY KEY ([COD_PRODUTO]),
    CONSTRAINT [FK_COD_TIPO_PRODUTO] FOREIGN KEY ([COD_TIPO_PRODUTO]) REFERENCES TIPO_PRODUTO(COD_TIPO_PRODUTO)
);

CREATE UNIQUE INDEX [IPK_COD_PRODUTO] ON [PRODUTO]([COD_PRODUTO]);

-----------------------------------------------------------------------------------
-- Criando a tabela Tipo Produto
---------------------------------
CREATE TABLE [TIPO_PRODUTO]
(
    [COD_TIPO_PRODUTO] NVARCHAR(160) NOT NULL,
    [DESCRICAO] NVARCHAR(160)  NOT NULL,

    CONSTRAINT [PK_COD_TIPO_PRODUTO] PRIMARY KEY ([COD_TIPO_PRODUTO])
);

CREATE UNIQUE INDEX [IPK_COD_TIPO_PRODUTO] ON [TIPO_PRODUTO]([COD_TIPO_PRODUTO]);

-----------------------------------------------------------------------------------
-- Criando a tabela Item Pedido Venda
--------------------------------
CREATE TABLE [ITEM_PEDIDO_VENDA]
(
    [COD_ITEM_PEDIDO_VENDA] NVARCHAR(160) NOT NULL,
    [COD_PEDIDO_VENDA] NVARCHAR(160)  NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [QTD_ITEM_PEDIDO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_ITEM_PEDIDO_VENDA] PRIMARY KEY ([COD_ITEM_PEDIDO_VENDA]),
    CONSTRAINT [FK_COD_PEDIDO_VENDA] FOREIGN KEY ([COD_PEDIDO_VENDA]) REFERENCES PEDIDO_VENDA(COD_PEDIDO_VENDA),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Item Pedido Compra
------------------------------
CREATE TABLE [ITEM_PEDIDO_COMPRA]
(
    [COD_ITEM_PEDIDO_COMPRA] NVARCHAR(160) NOT NULL,
    [COD_PEDIDO_COMPRA] NVARCHAR(160)  NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [QTD_ITEM_PEDIDO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_ITEM_PEDIDO_COMPRA] PRIMARY KEY ([COD_ITEM_PEDIDO_COMPRA]),
    CONSTRAINT [FK_COD_PEDIDO_COMPRA] FOREIGN KEY ([COD_PEDIDO_COMPRA]) REFERENCES PEDIDO_COMPRA(COD_PEDIDO_COMPRA),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Pedido Compra
-----------------------------
CREATE TABLE [PEDIDO_COMPRA]
(
    [COD_PEDIDO_COMPRA] NVARCHAR(160) NOT NULL,
    [COD_FORNECEDOR] NVARCHAR(160)  NOT NULL,
    [VLR_PRODUTO_COMPRA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_PEDIDO_COMPRA] PRIMARY KEY ([COD_PEDIDO_COMPRA]),
    CONSTRAINT [FK_COD_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
    
);

CREATE UNIQUE INDEX [IPK_COD_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Cotacao
--------------------------------
CREATE TABLE [COTACAO]
(
    [COD_COTACAO] NVARCHAR(160) NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [COD_FORNECEDOR] NVARCHAR(160)  NOT NULL,
    [VLR_COTACAO] DOUBLE NOT NULL,
    [UNIDADE_MEDIDA] NVARCHAR(160)  NOT NULL,


    CONSTRAINT [PK_COD_COTACAO] PRIMARY KEY ([COD_COTACAO]),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO),
    CONSTRAINT [FK_COD_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);
-----------------------------------------------------------------
-- Criando a tabela Cliente
--------------------------------
CREATE TABLE [CLIENTE]
(
    [COD_CLIENTE] NVARCHAR(160) NOT NULL,
    [NOME] NVARCHAR(160) NOT NULL,
    [TELEFONE] NVARCHAR(160) NOT NULL,
    [ENDERECO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_CLIENTE] PRIMARY KEY ([COD_CLIENTE])
    
);

CREATE UNIQUE INDEX [IPK_COD_CLIENTE] ON [CLIENTE]([COD_CLIENTE]);
-----------------------------------------------------------------
-- Criando a tabela Fornecedor 
-------------------------------
CREATE TABLE [FORNECEDOR]
(
    [COD_FORNECEDOR] NVARCHAR(160) NOT NULL,
    [NOME] NVARCHAR(160) NOT NULL,
    [TELEFONE] NVARCHAR(160) NOT NULL,
    [ENDERECO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_FORNECEDOR] PRIMARY KEY ([COD_FORNECEDOR])
);

CREATE UNIQUE INDEX [IPK_COD_FORNECEDOR] ON [FORNECEDOR]([COD_FORNECEDOR]);

-----------------------------------------------------------------
-- Criando a tabela Forma_Pagamento 
-------------------------------
CREATE TABLE [FORMA_PAGAMENTO]
(
    [COD_FORMA_PAGAMENTO] NVARCHAR(160) NOT NULL,
    [FORMA_PAGAMENTO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_FORMA_PAGAMENTO] PRIMARY KEY ([COD_FORMA_PAGAMENTO])
);

CREATE UNIQUE INDEX [IPK_COD_FORMA_PAGAMENTO] ON [FORMA_PAGAMENTO]([COD_FORMA_PAGAMENTO]);

-----------------------------------------------------------------
-- Criando a tabela Situacao Pedido
-----------------------------
CREATE TABLE [SITUACAO_PEDIDO]
(
    [COD_SITUACAO_PEDIDO] NVARCHAR(160) NOT NULL,
    [STATUS_PEDIDO] NVARCHAR(160) NOT NULL,
    [STATUS_PAGAMENTO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_SITUACAO_PEDIDO] PRIMARY KEY ([COD_SITUACAO_PEDIDO])
);

CREATE UNIQUE INDEX [IPK_COD_SITUACAO_PEDIDO] ON [SITUACAO_PEDIDO]([COD_SITUACAO_PEDIDO]);

-- Para deletar as tabelas:
DROP TABLE PEDIDO_VENDA
DROP TABLE VENDEDOR
DROP TABLE PRODUTO
DROP TABLE TIPO_PRODUTO
DROP TABLE ITEM_PEDIDO_VENDA
DROP TABLE ITEM_PEDIDO_COMPRA
DROP TABLE PEDIDO_COMPRA
DROP TABLE COTACAO
DROP TABLE CLIENTE
DROP TABLE FORNECEDOR
DROP TABLE FORMA_PAGAMENTO
DROP TABLE SITUACAO_PEDIDO

-----------------------------------------------------------------
-- CRUD (Create, Read, Update and Delete)

-- INSERT
-- Inserindo um registro na tabela PEDIDO_VENDA
INSERT INTO PEDIDO_VENDA (COD_PEDIDO_VENDA, COD_CLIENTE, COD_VENDEDOR, COD_SITUACAO_PEDIDO, COD_FORMA_PAGAMENTO,DATA_PEDIDO, VLR_PEDIDO_VENDA)
VALUES (20, 'Kayque', 'Pizza House', 'EM ANDAMENTO','Cartao','2023-07-08 19:00:00', 39.90);

-- Inserindo um registro na tabela VENDEDOR
INSERT INTO VENDEDOR (COD_VENDEDOR, NOME, TELEFONE, ENDERECO)
VALUES ('Pizza House', 'Kayque', 31988888888, 'Rua da Pizza');

-- Inserindo um registro na tabela Produto
INSERT INTO PRODUTO (COD_PRODUTO, COD_TIPO_PRODUTO, NOME, VLR_PRODUTO_COMPRA, VLR_PRODUTO_VENDA)
VALUES (20, 'pizza de frango com Catupiry','Pizza', 29.9, 42.9);

-- Inserindo um registro na tabela Item Pedido Venda
INSERT INTO ITEM_PEDIDO_VENDA (COD_ITEM_PEDIDO_VENDA, COD_PEDIDO_VENDA, COD_PRODUTO, QTD_ITEM_PEDIDO_VENDA)
VALUES ('P1', 1,20, 1);

-- Inserindo um registro na tabela Item Pedido Compra
INSERT INTO ITEM_PEDIDO_COMPRA (COD_ITEM_PEDIDO_COMPRA, COD_PEDIDO_COMPRA, COD_PRODUTO, QTD_ITEM_PEDIDO_VENDA)
VALUES ('C1', 1,20, 1);

-- Inserindo um registro na tabela Pedido Compra
INSERT INTO PEDIDO_COMPRA (COD_PEDIDO_COMPRA, COD_FORNECEDOR, VLR_PRODUTO_COMPRA)
VALUES ('P1', 'Pizza House', 40, );

-- Inserindo um registro na tabela Cotação
INSERT INTO COTACAO (COD_COTACAO, COD_PRODUTO, COD_FORNECEDOR, VLR_COTACAO, UNIDADE_MEDIDA)
VALUES ('COT1', 20, 'Pizza House', 4.99, 'QUALQUER');

-- Inserindo um registro na tabela Cliente
INSERT INTO CLIENTE (COD_CLIENTE, NOME, TELEFONE, ENDERECO)
VALUES ('Kayque', 'Kayque', 3133445566, 'Rua da casa');

-- Inserindo um registro na tabela FORNECEDOR
INSERT INTO FORNECEDOR (COD_FORNECEDOR, NOME, TELEFONE, ENDERECO)
VALUES ('Pizza House', 'Pizza House', 3133445588, 'Rua da Pizza');

-- Inserindo um registro na tabela FORMA_PAGAMENTO
INSERT INTO FORMA_PAGAMENTO (COD_FORMA_PAGAMENTO, FORMA_PAGAMENTO)
VALUES ('MASTERCARD', 'Cartao');

-- Inserindo um registro na tabela SITIACAO_PEDIDO
INSERT INTO SITUACAO_PEDIDO (COD_SITUACAO_PEDIDO, STATUS_PEDIDO, STATUS_PAGAMENTO)
VALUES ('SP20','EM ANDAMENTO', 'REALIZADO');
-----------------------------------------------------------------
-- SELECT 
--------------------------------
-- Abrindo Dados PEDIDO_VENDA
SELECT * FROM PEDIDO_VENDA WHERE COD_CLIENTE LIKE 'Kayque%';

-- Abrindo Dados VENDEDOR
SELECT * FROM VENDEDOR WHERE NOME LIKE 'Kayque%';

-- Abrindo Dados PRODUTO
SELECT * FROM PRODUTO WHERE COD_TIPO_PRODUTO LIKE '%frango%'
    
-- Abrindo Dados ITEM_PEDIDO_VENDA
SELECT * FROM ITEM_PEDIDO_VENDA WHERE COD_ITEM_PEDIDO_VENDA LIKE '%P1%'
    
-- Abrindo Dados ITEM_PEDIDO_COMPRA
SELECT * FROM ITEM_PEDIDO_COMPRA WHERE COD_ITEM_PEDIDO_COMPRA LIKE  '%C1%'

-- Abrindo Dados PEDIDO_COMPRA
SELECT * FROM PEDIDO_COMPRA WHERE COD_PEDIDO_COMPRA LIKE '%P1%'

-- Abrindo Dados COTACAO
SELECT * FROM COTACAO WHERE COD_COTACAO LIKE '%COT1%'

-- Abrindo Dados CLIENTE
SELECT * FROM CLIENTE WHERE COD_CLIENTE LIKE '%Kayque%'

-- Abrindo Dados FORNECEDOR
SELECT * FROM FORNECEDOR WHERE COD_FORNECEDOR LIKE '%PIZZA%'

-- Abrindo Dados FORMA_PAGAMENTO
SELECT * FROM FORMA_PAGAMENTO WHERE COD_FORMA_PAGAMENTO LIKE '%MASTERCARD%'

-- Abrindo Dados SITUACAO_PEDIDO
SELECT * FROM SITUACAO_PEDIDO WHERE COD_SITUACAO_PEDIDO LIKE '%SP20%'
