-----------------------------------------------------------------------------------
-- Criando a tabela PEDIDO_VENDA
--------------------------------
CREATE TABLE [PEDIDO_VENDA]
(
    [COD_PEDIDO_VENDA] NVARCHAR(160)  NOT NULL,
    [COD_CLIENTE] NVARCHAR(160)  NOT NULL,
    [COD_VENDEDOR] NVARCHAR(160)  NOT NULL,
    [COD_SITUACAO_PEDIDO] NVARCHAR(160)  NOT NULL,
    [COD_FORMA_PAGAMENTO] NVARCHAR(160)  NOT NULL,
    [DATA_PEDIDO] DATETIME NOT NULL,
    [VLR_PEDIDO_VENDA] DOUBLE NOT NULL, 

    CONSTRAINT [PK_PEDIDO_VENDA] PRIMARY KEY ([COD_PEDIDO_VENDA]),
    CONSTRAINT [FK_COD_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES CLIENTE(COD_CLIENTE),
    CONSTRAINT [FK_COD_VENDEDOR] FOREIGN KEY ([COD_VENDEDOR]) REFERENCES VENDEDOR(COD_VENDEDOR),
    CONSTRAINT [FK_COD_SITUACAO_PEDIDO] FOREIGN KEY ([COD_SITUACAO_PEDIDO]) REFERENCES SITUACAO_PEDIDO(COD_SITUACAO_PEDIDO),
    CONSTRAINT [FK_COD_FORMA_PAGAMENTO] FOREIGN KEY ([COD_FORMA_PAGAMENTO]) REFERENCES FORMA_PAGAMENTO(COD_FORMA_PAGAMENTO)
);

CREATE UNIQUE INDEX [IPK_PEDIDO_VENDA] ON [PEDIDO_VENDA]([COD_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela VENDEDOR
---------------------------------
CREATE TABLE [VENDEDOR]
(
    [COD_VENDEDOR] NVARCHAR(160)  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    
    CONSTRAINT [PK_COD_VENDEDOR] PRIMARY KEY ([COD_VENDEDOR])
);

CREATE UNIQUE INDEX [IPK_COD_VENDEDOR] ON [VENDEDOR]([COD_VENDEDOR]);

-----------------------------------------------------------------------------------
-- Criando a tabela Produto
------------------------------------
CREATE TABLE [PRODUTO]
(
    [COD_PRODUTO] NVARCHAR(160) NOT NULL,
    [COD_TIPO_PRODUTO] NVARCHAR(160)  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [VLR_PRODUTO_COMPRA] DOUBLE NOT NULL,
    [VLR_PRODUTO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_PRODUTO] PRIMARY KEY ([COD_PRODUTO]),
    CONSTRAINT [FK_COD_TIPO_PRODUTO] FOREIGN KEY ([COD_TIPO_PRODUTO]) REFERENCES TIPO_PRODUTO(COD_TIPO_PRODUTO)
);

CREATE UNIQUE INDEX [IPK_COD_PRODUTO] ON [PRODUTO]([COD_PRODUTO]);

-----------------------------------------------------------------------------------
-- Criando a tabela Tipo Produto
---------------------------------
CREATE TABLE [TIPO_PRODUTO]
(
    [COD_TIPO_PRODUTO] NVARCHAR(160) NOT NULL,
    [DESCRICAO] NVARCHAR(160)  NOT NULL,

    CONSTRAINT [PK_COD_TIPO_PRODUTO] PRIMARY KEY ([COD_TIPO_PRODUTO])
);

CREATE UNIQUE INDEX [IPK_COD_TIPO_PRODUTO] ON [TIPO_PRODUTO]([COD_TIPO_PRODUTO]);

-----------------------------------------------------------------------------------
-- Criando a tabela Item Pedido Venda
--------------------------------
CREATE TABLE [ITEM_PEDIDO_VENDA]
(
    [COD_ITEM_PEDIDO_VENDA] NVARCHAR(160) NOT NULL,
    [COD_PEDIDO_VENDA] NVARCHAR(160)  NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [QTD_ITEM_PEDIDO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_ITEM_PEDIDO_VENDA] PRIMARY KEY ([COD_ITEM_PEDIDO_VENDA]),
    CONSTRAINT [FK_COD_PEDIDO_VENDA] FOREIGN KEY ([COD_PEDIDO_VENDA]) REFERENCES PEDIDO_VENDA(COD_PEDIDO_VENDA),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Item Pedido Compra
------------------------------
CREATE TABLE [ITEM_PEDIDO_COMPRA]
(
    [COD_ITEM_PEDIDO_COMPRA] NVARCHAR(160) NOT NULL,
    [COD_PEDIDO_COMPRA] NVARCHAR(160)  NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [QTD_ITEM_PEDIDO_VENDA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_ITEM_PEDIDO_COMPRA] PRIMARY KEY ([COD_ITEM_PEDIDO_COMPRA]),
    CONSTRAINT [FK_COD_PEDIDO_COMPRA] FOREIGN KEY ([COD_PEDIDO_COMPRA]) REFERENCES PEDIDO_COMPRA(COD_PEDIDO_COMPRA),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Pedido Compra
-----------------------------
CREATE TABLE [PEDIDO_COMPRA]
(
    [COD_PEDIDO_COMPRA] NVARCHAR(160) NOT NULL,
    [COD_FORNECEDOR] NVARCHAR(160)  NOT NULL,
    [VLR_PRODUTO_COMPRA] DOUBLE NOT NULL,

    CONSTRAINT [PK_COD_ITEM_PEDIDO_COMPRA] PRIMARY KEY ([COD_ITEM_PEDIDO_COMPRA]),
    CONSTRAINT [FK_COD_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-----------------------------------------------------------------------------------
-- Criando a tabela Cotacao
--------------------------------
(
    [COD_COTACAO] NVARCHAR(160) NOT NULL,
    [COD_PRODUTO] NVARCHAR(160)  NOT NULL,
    [COD_FORNECEDOR] NVARCHAR(160)  NOT NULL,
    [VLR_COTACAO] DOUBLE NOT NULL,
    [UNIDADE_MEDIDA] NVARCHAR(160)  NOT NULL,


    CONSTRAINT [PK_COD_COTACAO] PRIMARY KEY ([COD_COTACAO]),
    CONSTRAINT [FK_COD_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO),
    CONSTRAINT [FK_COD_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
    
);

CREATE UNIQUE INDEX [IPK_COD_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);
-----------------------------------------------------------------
-- Criando a tabela Cliente
--------------------------------
CREATE TABLE [CLIENTE]
(
    [COD_CLIENTE] NVARCHAR(160) NOT NULL,
    [NOME] NVARCHAR(160) NOT NULL,
    [TELEFONE] NVARCHAR(160) NOT NULL,
    [ENDERECO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_CLIENTE] PRIMARY KEY ([COD_CLIENTE])
    
);

CREATE UNIQUE INDEX [IPK_COD_CLIENTE] ON [CLIENTE]([COD_CLIENTE]);
-----------------------------------------------------------------
-- Criando a tabela Fornecedor 
-------------------------------
CREATE TABLE [FORNECEDOR]
(
    [COD_FORNECEDOR] NVARCHAR(160) NOT NULL,
    [NOME] NVARCHAR(160) NOT NULL,
    [TELEFONE] NVARCHAR(160) NOT NULL,
    [ENDERECO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_FORNECEDOR] PRIMARY KEY ([COD_FORNECEDOR])
);

CREATE UNIQUE INDEX [IPK_COD_FORNECEDOR] ON [FORNECEDOR]([COD_FORNECEDOR]);

-----------------------------------------------------------------
-- Criando a tabela Forma_Pagamento 
-------------------------------
CREATE TABLE [FORMA_PAGAMENTO]
(
    [COD_FORMA_PAGAMENTO] NVARCHAR(160) NOT NULL,
    [FORMA_PAGAMENTO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_FORMA_PAGAMENTO] PRIMARY KEY ([COD_FORMA_PAGAMENTO])
);

CREATE UNIQUE INDEX [IPK_COD_FORMA_PAGAMENTO] ON [FORMA_PAGAMENTO]([COD_FORMA_PAGAMENTO]);

-----------------------------------------------------------------
-- Criando a tabela Situacao Pedido
-----------------------------
CREATE TABLE [SITUACAO_PEDIDO]
(
    [COD_SITUACAO_PEDIDO] NVARCHAR(160) NOT NULL,
    [STATUS_PEDIDO] NVARCHAR(160) NOT NULL,
    [STATUS_PAGAMENTO] NVARCHAR(160) NOT NULL,

    CONSTRAINT [PK_COD_SITUACAO_PEDIDO] PRIMARY KEY ([COD_SITUACAO_PEDIDO])
);

CREATE UNIQUE INDEX [IPK_COD_SITUACAO_PEDIDO] ON [SITUACAO_PEDIDO]([COD_SITUACAO_PEDIDO]);

-- Para deletar as tabelas:
DROP TABLE PEDIDO_VENDA
DROP TABLE VENDEDOR
DROP TABLE PRODUTO
DROP TABLE TIPO_PRODUTO
DROP TABLE ITEM_PEDIDO_VENDA
DROP TABLE ITEM_PEDIDO_COMPRA
DROP TABLE PEDIDO_COMPRA
DROP TABLE COTACAO
DROP TABLE CLIENTE
DROP TABLE FORNECEDOR
DROP TABLE FORMA_PAGAMENTO
DROP TABLE SITUACAO_PEDIDO

-----------------------------------------------------------------
-- CRUD (Create, Read, Update and Delete)

-- INSERT
-- Inserindo um registro na tabela PEDIDO_VENDA
INSERT INTO PEDIDO_VENDA (COD_PEDIDO_VENDA, COD_CLIENTE, COD_VENDEDOR, COD_SITUACAO_PEDIDO, COD_FORMA_PAGAMENTO,DATA_PEDIDO, VLR_PEDIDO_VENDA)
VALUES (20, 'Kayque', 'Pizza House', 'EM ANDAMENTO','Cartao','2023-07-08 19:00:00', 39.90);

-- Inserindo um registro na tabela VENDEDOR
INSERT INTO VENDEDOR (COD_VENDEDOR, NOME, TELEFONE, ENDERECO)
VALUES ('Pizza House', 'Kayque', 31988888888, 'Rua da Pizza');

-- Inserindo um registro na tabela Produto
INSERT INTO PRODUTO (COD_PRODUTO, COD_TIPO_PRODUTO, NOME, VLR_PRODUTO_COMPRA, VLR_PRODUTO_VENDA)
VALUES (20, 'pizza de frango com Catupiry','Pizza', 29.9, 42.9);
-----------------------------------------------------------------
-- SELECT 
--------------------------------
SELECT * FROM PEDIDO_VENDA WHERE COD_CLIENTE LIKE 'Kayque%';
SELECT * FROM VENDEDOR WHERE NOME LIKE 'Kayque%';
SELECT * FROM PRODUTO WHERE COD_TIPO_PRODUTO LIKE '%frango%'
